import type { Metadata } from "next"
import { IBM_Plex_Mono, Lora, Plus_Jakarta_Sans } from "next/font/google"

import { NuqsAdapter } from "nuqs/adapters/next/app"

import { getToken } from "@/lib/auth-server"
import { ConvexClientProvider } from "@/provider/ConvexClientProvider"

import "./globals.css"

const fontSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const fontSerif = Lora({
  subsets: ["latin"],
  variable: "--font-serif",
})

const fontMono = IBM_Plex_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = await getToken()

  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <NuqsAdapter>
          <ConvexClientProvider initialToken={token}>
            {children}
          </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
